version: '3'

services:
  app:
    container_name: node-api
    build:
      context: ./src
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - MONGO_DATABASE=mongodb://mongodb/myapp
      - GITHUB_USER_NAME=sample
      - GITHUB_USER_PASSWORD=sample
      - GITHUB_ORGANIZATION_NAME=tetsu-tech
      - GITHUB_REPOSITORY_NAME=hackathon-sandbox
      - BASIC_USER=sample
      - BASIC_PASSWORD=sample
    volumes:
      - ./src:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8080
    tty: true
    links:
      - mongodb

  # ローカルホストの27017 portと繋ぐ
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    # すでにportを使っている場合はホストマシン側のportを変更する
    ports:
      - 27017:27017
    command:
      - mongod
